/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiGenerateCaptionRouteImport } from './routes/api/generate-caption'
import { Route as ApiCatImageRouteImport } from './routes/api/cat-image'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateCaptionRoute = ApiGenerateCaptionRouteImport.update({
  id: '/api/generate-caption',
  path: '/api/generate-caption',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCatImageRoute = ApiCatImageRouteImport.update({
  id: '/api/cat-image',
  path: '/api/cat-image',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/cat-image': typeof ApiCatImageRoute
  '/api/generate-caption': typeof ApiGenerateCaptionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/cat-image': typeof ApiCatImageRoute
  '/api/generate-caption': typeof ApiGenerateCaptionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/cat-image': typeof ApiCatImageRoute
  '/api/generate-caption': typeof ApiGenerateCaptionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/cat-image' | '/api/generate-caption'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/cat-image' | '/api/generate-caption'
  id: '__root__' | '/' | '/api/cat-image' | '/api/generate-caption'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiCatImageRoute: typeof ApiCatImageRoute
  ApiGenerateCaptionRoute: typeof ApiGenerateCaptionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-caption': {
      id: '/api/generate-caption'
      path: '/api/generate-caption'
      fullPath: '/api/generate-caption'
      preLoaderRoute: typeof ApiGenerateCaptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cat-image': {
      id: '/api/cat-image'
      path: '/api/cat-image'
      fullPath: '/api/cat-image'
      preLoaderRoute: typeof ApiCatImageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiCatImageRoute: ApiCatImageRoute,
  ApiGenerateCaptionRoute: ApiGenerateCaptionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
